package com.example.notalone.enums;

public enum Positives {
    ISKRENNOST,
    STRESSOUSTOUCHIVOST,
    ORGANIZOVANNOST,
    VNIMATELNOST,
    SCHEDROST,
    TRUDOLUBIE,
    ZHIZNERADOSTNOST,
    SPOSOBNOST_BLAGODARIT,
    ZDRAVOMYSLIE,
    TERPELIVOST,
    BEREZHLIVOST,
    MUDROST,
    OTZUVCHIVOST,
    SMELOST,
    CREATIVNOST,
    CHUVSTVO_YOUMORA,
    INICIATIVNOST,
    PUNKTUALNOST,
    SKROMNOST,
    UVERENNOST
}
